### ISSUE TITLE
[BUG] Can't use classifiers due to mismatch 

### ISSUE THREAD

**Issue by smithct2** [BGebken/Linnaeus-Classifier#16]
**Describe the bug**
Hey Bennett,

I have started to get errors when trying to use the classifiers since I downloaded the newest vectorizer.pkl (uploaded to GitHub this morning, 04/12/19, in commit "Fixed Model") and the newest LRclf.pkl (uploaded to Dropbox this morning, 04/12/19).

I now get this error:
```
X has 147928 features per sample; expecting 147625.
```

**Expected behavior**
"text_prob" is supposed to be the probabilities, instead it returns the above error.
```
claim_text = (some string claim text sent to the service)
clf = joblib.load(filename="src/main/python/LRclf.pkl")
vectorizer = joblib.load(filename="src/main/python/vectorizer.pkl")
text_vector = vectorizer.transform([claim_text])
text_prob = clf.predict_proba(text_vector)
```

Can you please upload/update the latest of both pickles to here/Dropbox so I can use the working versions?

Thanks,
Chris

**Comment by BGebken** [comment]
Added the latest version of "vectorizer.pkl" and "LRclf.pkl" to the GitHub (https://www.dropbox.com/sh/zy740dkr938vwcn/AAAdKbIM3JWHrtM-5ZuhLVf8a?dl=0) (Read-Only Link)

Also, tested Linnaeus_Classifier.py with these inputs and appears to be working properly

**Comment by BGebken** [comment]
Please verify if further troubleshooting is needed!

**Comment by smithct2** [comment]
Yep, works now...thanks!
